In [3]:
#Import libraires
import pandas as pd
from selenium.webdriver.common.by import By
import time
from selenium import webdriver
from datetime import datetime
from selenium.webdriver.chrome.service import Service

In [4]:
#path for chrome webdriver
path=Service("C:\selenium drivers\chromedriver.exe")
op = webdriver.ChromeOptions()

####  *Bitcoin Historical data only available from April 28 2013 to till date in the Coin Marketcap website*

In [5]:
date_1 = '1/1/2022'
date_2 = '16/6/2022'
start = datetime.strptime(date_1, "%d/%m/%Y")
end =   datetime.strptime(date_2, "%d/%m/%Y")
diff = (end.year - start.year) * 12 + (end.month  - start.month )
no_of_month=diff#It decides number of time to click load more button in coinmarketcap historical page 
delta = end.date() - start.date()
no_of_records=int(delta.days)#It iterate the each days using no of records var

#### *You can also customize your start and end date of time period by changing above code and choose your favorite coin below to scrap the historical data*

In [6]:
select_coins=['bitcoin','ethereum','bnb','solana','polkadot-new','cardano']
coin_choosen=input(f"Select Number to choose coin \n Bitcoin(1) \n Ethereum(2) \n BNB(3) \n Solana(4) \n Polkadot(5) \n Cardano(6)")
coin_chosen_by_user=select_coins[int(coin_choosen)-1]
print(coin_chosen_by_user)

Select Number to choose coin
 Bitcoin(1)
 Ethereum(2)
 BNB(3)
 Solana(4)
 Polkadot(5)
 Cardano(6) 1

bitcoin

#### *Scraping the Data from Coin Marketcap*

In [7]:
#main code here
try:
    date_list=[]
    open_price_list=[]
    high_price_list=[]
    low_price_list=[]
    close_price_list=[]
    volume_list=[]
    market_cap_list=[]
    #URL path
    driver = webdriver.Chrome(service=path, options=op)
    # For maximizing window
    driver.maximize_window()
    # Implicit wait apply for all elements to wait for 5 seconds to load
    driver.implicitly_wait(5)
    driver.get("https://coinmarketcap.com/currencies/bitcoin/historical-data/")
    time.sleep(3)
    driver.find_element(by=By.XPATH,value="//*[@id='cmc-cookie-policy-banner']/div[2]").click()
    for j in range(1,no_of_month):
        time.sleep(3)
        driver.find_element(by=By.XPATH,value='//button[normalize-space()="Load More"]').click()
        
    for i in range(1,no_of_records+2):
        
        #Accessing coin date, open_price,close_price_low_price_high_price,,volume_24hr_change, Mkt_Cap using the element xpath

        date=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[1]")
        open_price=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[2]")
        high_price=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[3]")
        low_price=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[4]")
        close_price=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[5]")
        volume=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[6]")
        mak_cap=driver.find_element(by=By.XPATH,value="//*[@id='__next']/div[1]/div[1]/div[2]/div/div[3]/div/div/div[1]/div[2]/table/tbody/tr["+str(i)+"]/td[7]")
        
        #Appending all Data into respective records
        date_list.append(date.text.strip())
        open_price_list.append(open_price.text.strip())
        high_price_list.append(high_price.text.strip())
        low_price_list.append(low_price.text.strip())
        close_price_list.append(close_price.text.strip())
        volume_list.append(volume.text.strip())
        market_cap_list.append(mak_cap.text.strip())

except:
    #setting time to close after 2 sec
    time.sleep(3)
    driver.close()
finally:
    time.sleep(3)
    driver.close()

#### *Creating Dataframe from scraped results*

In [8]:
#Create Pandas DataFame
bitcoin_df1=pd.DataFrame({"Date":date_list,"Open Price":open_price_list,"High Price":high_price_list,"Low Price":low_price_list,"Close Price":close_price_list,"Volume_24hr":volume_list,"Market Cap":market_cap_list})

In [9]:
#Display first 10 records
bitcoin_df1.head(10)

,Date,Open Price,High Price,Low Price,Close Price,Volume_24hr,Market Cap
0,"Jun 16, 2022","$22,576.31","$22,868.92","$20,265.23","$20,381.65","$31,183,975,654","$388,664,840,557"
1,"Jun 15, 2022","$22,196.73","$22,642.67","$20,178.38","$22,572.84","$54,912,007,015","$430,432,160,006"
2,"Jun 14, 2022","$22,487.99","$23,018.95","$20,950.82","$22,206.79","$50,913,575,242","$423,429,131,864"
3,"Jun 13, 2022","$26,737.58","$26,795.59","$22,141.26","$22,487.39","$68,204,556,440","$428,759,852,105"
4,"Jun 12, 2022","$28,373.51","$28,502.69","$26,762.65","$26,762.65","$34,163,220,274","$510,252,464,821"
5,"Jun 11, 2022","$29,084.67","$29,401.92","$28,236.21","$28,360.81","$27,246,574,439","$540,698,499,860"
6,"Jun 10, 2022","$30,110.33","$30,245.81","$28,978.15","$29,083.80","$29,867,476,527","$554,455,834,486"
7,"Jun 09, 2022","$30,215.28","$30,609.31","$30,020.26","$30,112.00","$21,692,004,719","$574,029,141,739"
8,"Jun 08, 2022","$31,151.48","$31,253.69","$29,944.40","$30,214.36","$30,242,059,107","$575,953,219,488"
9,"Jun 07, 2022","$31,371.74","$31,489.68","$29,311.68","$31,155.48","$40,770,974,039","$593,857,882,017"

In [10]:
bitcoin_df1.tail(10)

,Date,Open Price,High Price,Low Price,Close Price,Volume_24hr,Market Cap
157,"Jan 10, 2022","$41,910.23","$42,199.49","$39,796.57","$41,821.26","$32,104,232,331","$791,484,886,194"
158,"Jan 09, 2022","$41,734.73","$42,663.95","$41,338.16","$41,911.60","$21,294,384,372","$793,156,354,744"
159,"Jan 08, 2022","$41,561.47","$42,228.94","$40,672.28","$41,733.94","$28,066,355,845","$789,758,782,727"
160,"Jan 07, 2022","$43,153.57","$43,153.57","$41,077.45","$41,557.90","$84,196,607,520","$786,389,774,194"
161,"Jan 06, 2022","$43,565.51","$43,748.72","$42,645.54","$43,160.93","$30,208,048,289","$816,685,390,313"
162,"Jan 05, 2022","$45,899.36","$46,929.05","$42,798.22","$43,569.00","$36,851,084,859","$824,368,284,530"
163,"Jan 04, 2022","$46,458.85","$47,406.55","$45,752.46","$45,897.58","$42,494,677,905","$868,383,282,082"
164,"Jan 03, 2022","$47,343.54","$47,510.73","$45,835.96","$46,458.12","$33,071,628,362","$878,946,596,803"
165,"Jan 02, 2022","$47,680.93","$47,881.41","$46,856.94","$47,345.22","$27,951,569,547","$895,688,387,523"
166,"Jan 01, 2022","$46,311.74","$47,827.31","$46,288.49","$47,686.81","$24,582,667,004","$902,104,193,385"

#### *Saving the data*

In [9]:
#writing to csv
bitcoin_df1.to_csv("Bitcoin Historical Data_April_2013_28_to_June_2022_15.csv",index=False)

In [25]:
#writing to excel
bitcoin_df1.to_excel('Bitcoin Historical Data_April_2013_28_to_June_2022_15_omg.xlsx',sheet_name='Bitcoin_history_coins',index=False)

In [14]:
# bitcoin_df1.to_excel('Bitcoin Historical Data_April_2013_28_to_June_2022_15.xlsx',sheet_name='Bitcoin_history_coins',engine='xlsxwriter',index=False)